name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest    
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
    - run: nix-build
    - run: nix-build ./overlays/20-emacs/emacs/default.nix
    - run: nix-env -f default.nix -i
    - run: dotfiles install
    - run: dotfiles link
    - run: dotfiles uninstall
    - name: Docs
      uses: purcell/setup-emacs@master
      with:
        version: 26.3
    - run: cd docs && ./overlays/20-emacs/emacs/result/bin/emacs -Q index.org --batch --eval "(progn (org-babel-tangle)(org-html-export-to-html))" --kill
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        local-dir: docs
        target-branch: gh-pages
        cname: dotfiles.codearsonist.com
        publish_dir: ./site
